### ISSUE TITLE
Enhancement request: use Vim ctrl-p and ctrl-n directly

### ISSUE THREAD

**Issue by RhvdG** [Yeboster/autocomplete-obsidian#12]
I'm very happy with your plugin! But I'd like to use the Vim ctrl-p and ctrl-n commands directly, like in Vim, without first using ctrl-space. Is that possible?

**Comment by Yeboster** [comment]
Hi!
Indeed this is a nice feature to have. Expect it in the next release!

**Comment by RhvdG** [comment]
Wonderful! Looking forward to it.

**Comment by Yeboster** [comment]
Hi @RhvdG,
I've just released the v 0.7.4 which contains the "trigger like vim" option in the settings (disabled by default). Please let me know if it works correctly 👍

**Comment by RhvdG** [comment]
> Hi @RhvdG,
> I've just released the v 0.7.4 which contains the "trigger like vim" option in the settings (disabled by default). Please let me know if it works correctly 👍

It works perfectly. Thanks!

**Comment by Yeboster** [comment]
Nice! Closing the issue
