### ISSUE TITLE
Latex completion doesn't work next to $

### ISSUE THREAD

**Issue by Arax20** [Yeboster/autocomplete-obsidian#13]
Latex autocomplete does not work when the string is next to the delimiter `$`:
![image](https://user-images.githubusercontent.com/45805601/116275158-8d7ea480-a7ad-11eb-9906-e9b239ecc77f.png)
![image](https://user-images.githubusercontent.com/45805601/116274965-58725200-a7ad-11eb-8927-701e01311027.png)

This is an issue since leaving a space means it no longer qualifies as latex.

**Comment by Yeboster** [comment]
Hi @Arax20,
thanks for your bug report. I will fix the issue in the next release.

**Comment by Columpio** [comment]
The same for the `&` symbol in the `align` environment. I think the bug may be common for other command prefixes as well.

**Comment by Yeboster** [comment]
I confirm this as well. A possible solution for all cases would be to detect the cursor is inside a latex block and then change the word separators to the latex one. This solution is quite expensive if you're using a latex block $$$$ because it expands on multiple lines

A faster solution to fix this is to let the user customise the word separators (this way latex users can omit the & and $).

What do you think @Columpio ? Have you some suggestions?

**Comment by Arax20** [comment]
My current workaround is that I'll place all of my latex inside one large bracket group so that I can get away with spaces between the borders and the inside text:
```latex
${ \frac{ a }{ b } = \mathrm{ some latex } }$
```

**Comment by Columpio** [comment]
@Yeboster , why not set latex separators to be default? (Or union of latex separators and usual ones).
I think, this should do the trick.

And you also cannot detect whether user is inside a latex block as the block may be not finished (like in OP example above).

**Comment by Arax20** [comment]
Obsidian already does latex block detection, as indicated by the syntax highlighting that occurs. Latex sections are of `cm-math` class. The active line is also indicated with class `Codemirror-activeline` so perhaps some sort of logic where you query for `div.CodeMirror-activeline` and then check if the descendent span is `cm-math`.

The issue I see is that you'd still have to manually parse the line to see if you're within a block for a given line but if you're using mutiline latex blocks then individual line parsing kind of falls apart. Might be a good palce to start though.

**Comment by Yeboster** [comment]
Thanks for your suggestions, highly appreciated!

@Columpio ,  have added some of those separators in the [https://github.com/Yeboster/autocomplete-obsidian/releases/tag/0.8.0.rc3](0.8.0.rc3) release (manual installation is required). I will try to make asap an release with those fixes along with a user customizable word separators.

Then I will follow @Arax20 nice suggestion to identify if the cursor is in a latex block. I will also check if the editor instance have some metadata about the current line, this way it should be way faster than parsing the file.

Unfortunately these weeks are quite busy for me at work, but I will try to find some time.

**Comment by Yeboster** [comment]
I've just released version 0.8.0 which has some word separators as $ and & to fix this issue. You can how even change word separators as you like 😄 

I'm going to create another issue to improve latex mode handling.
