### ISSUE TITLE
Latex env only completes for `\begin{` not for `\end{`

### ISSUE THREAD

**Issue by usualwitch** [Yeboster/autocomplete-obsidian#15]
Hi, I loaded this plugin and found it doesn't work for `\end{` completion inside `$$`. Is it a bug?

**Comment by Yeboster** [comment]
Hello @usualwitch,

There is no end in the completions, it's missing. I'm going to review the latex provider, probably using some library instead of listing them all. Do you have any suggestions ?

**Comment by usualwitch** [comment]
I usually write tex with vim, and my solution to entering begin/end pairs is just reading from a snippet file and then inserting on a new line. 

I don’t know js, so I plan to port my simple vimscript solution to obsidian vimrc. Is it possible for the autocomplete plugin to insert these begin/end in pairs?

**Comment by Yeboster** [comment]
Hello @usualwitch,
In the next release I will add the `\end` tag and in the following releases I will try to improve vim suggestions.

The begin/end pairs will be added with the snippets feature soon, right now I am refactoring the core.

Thanks for your patience,
have a nice day!

**Comment by Yeboster** [comment]
I've added `\end` tags in release 0.8.0. In the future I will improve latex mode handling.
