### ISSUE TITLE
Feature request: autocomplete on each input from the words in the note

### ISSUE THREAD

**Issue by mtomas7** [Yeboster/autocomplete-obsidian#16]
Thank you for this plugin!

would it be possible to autocomplete without a shortcut activation (on each input) and autocomplete from the words used in the note. Please see this post: https://forum.obsidian.md/t/what-keeps-you-from-the-final-switch-to-obsidian/18173

**Comment by Yeboster** [comment]
Hello there!

I'm developing this feature and expect a release soon. 
The next release will still have a partial scanning (it scans the file on load or change and scan last word on separator char (space, brackets) but this does not work well with some languages (e.g. Japanese)). I am also trying to find the best approach to have a background scanning while not impacting on cpu too much.

**Comment by Yeboster** [comment]
Hello @mtomas7,
please check this [pre-release 0.8.0.rc1](https://github.com/Yeboster/autocomplete-obsidian/releases/tag/0.8.0.rc1) that has auto trigger functionality. If there are any issues please let me know

**Comment by mtomas7** [comment]
Works great, thank you!

I have one suggestion: to increase performance even more, you need to implement "From n-th character" setting.

![](https://forum.obsidian.md/uploads/default/original/2X/4/458dfe316c0359f23edb674351ef590080fe5ef8.png)

Now, if I'm starting to type a short word like "the" or "us", autocomplete kicks in and I would say without a good reason, because many people have muscle memory to enter those common short words. If I could set the value for n=3, then my writing would be faster in terms of Obsidian performance, and I would avoid visual disruption while typing some short words.

Another question is related to the Latex Option. It is selected ON, but I'm not sure if I need it. Could you please add an example perhaps to the plugin write-up to make it easier to understand if I need it active, as it may decrease the performance.

Thank you and God bless you and your good works!

**Comment by mtomas7** [comment]
I also noticed that autocomplete activates on Paste. It feels awkward that after you paste an image or text and autocomplete box pops-up.

**Comment by Yeboster** [comment]
Hello @mtomas7,
I've published a new [release candidate 0.8.0.rc3](https://github.com/Yeboster/autocomplete-obsidian/releases/tag/0.8.0.rc3), with the fixes and feature you asked, now the autocomplete is even faster! Thanks for the "from n-th trigger" suggestion, that was a great performance improvement 😄 

I will test this in the next days but please let me know what do you think or if there are some issues 👍 

Have a nice day!

**Comment by mtomas7** [comment]
After first look, I would probably lower default option for n-th to 3, so first-time users would have it more pro-active, but that's just my opinion :)

I will let you know if something else comes up.

**Comment by mtomas7** [comment]
Autocomplete form still activates on CTRL+C.

**Comment by mtomas7** [comment]
and on CTRL+X

**Comment by mtomas7** [comment]
I think it is also good to disable autocomplete after sentence syntax symbols, eg: . , ; ! ? perhaps even :

**Comment by mtomas7** [comment]
It looks, that autocomplete pop-up box is limited by the Obsidian viewport dimensions. Can you make it float on top?

![image](https://user-images.githubusercontent.com/2348962/120722543-85ddaa00-c495-11eb-8eeb-26e9b43a8b6e.png)

**Comment by mtomas7** [comment]
When autocomplete pop-up is active and you start using arrow keys or mouse to navigate cursor, then:

- if using arrow keys: pop-up box follows the cursor giving all kinds of suggestions, depending on the cursors place.
- if using mouse: pop-up box stays active in the initial position.

I would imagine if someone was typing and then move the cursor by arrow keys or mouse, that means they are done with that word in either way (mouse or arrow key was pressed) pop-up box should be deactivated.

**Comment by mtomas7** [comment]
I would also disable the autocomplete for double-brackets, as Obsidian launches its own autocomplete for internal links.

**Comment by expat67** [comment]
would be possible to use TAB as trigger instead of ENTER? 
thank you

**Comment by mtomas7** [comment]
Or both: Enter and Tab ;)

**Comment by sohanglal** [comment]
I tried out the pre-release 0.8.0.rc3. It works like a charm! Thanks @Yeboster!

**Comment by Yeboster** [comment]
Thanks everybody for the suggestions and finally the time to release [0.8.0](https://github.com/Yeboster/autocomplete-obsidian/releases/tag/0.8.0) has arrived! Please check the changelog and try out the release :) 

I've still some left (close autocomplete on mouse out, improve layout positioning, disable autocomplete on double brackets) but I think it's enough for this awaited release. I will open two issues for the missing suggestions. Please write here for related things to auto trigger
