### ISSUE TITLE
Autocomplete hotkeys don't work with lists (UPD: Conflict with Outliner plugin configured by default)

### ISSUE THREAD

**Issue by l2aggron** [Yeboster/autocomplete-obsidian#22]
Hey!
It looks like there is a hotkey or focus issue in the autocomplete popup when combined with lists.
When I try to select a word from the autocomplete menu by tab - I have a line shift, when I try to press Enter - a carriage return occurs
There is a small gif explaining the problem: 
https://i.imgur.com/dGFWNG1.gif

**Comment by Yeboster** [comment]
Hi @l2aggron!
Thanks for you report. I've just tried to replicate your issue (obsidian 0.12.10, autocomplete 0.8.0) on an vanilla obsidian (only autocomplete plugin) but I cannot replicate your issue. 
Can you please test it on a vanilla vault (no plugins, just autocomplete) to check if the issue still occurs and if so, give me a list of reproducible steps ? If it doesn't happen on a vanilla workspace, there should be a plugin creating a conflict.

**Comment by l2aggron** [comment]
Hey! Thanks for the answer!
It looks like the problem occurs when the [Outliner plugin](https://github.com/vslinko/obsidian-outliner) with default settings is installed and enabled.
There is no problem when the outliner plugin is disabled.
Also, when I changed the highlighted setting of this plugin (screenshot) the enter key works fine 
![image](https://user-images.githubusercontent.com/25399254/125942723-0eb0c3d2-2698-46e8-82c0-92646c7d5648.png)

**Comment by Yeboster** [comment]
Hei @l2aggron, thanks for your feedback! This will be helpful for other people using this plugin. 
Also, I think I could add a line in the readme about the compatibility issues. 
I am closing this issue.
Do you have other suggestions?

**Comment by garahad** [comment]
thanks it works!!!!! wow !!!! wounderful
