### ISSUE TITLE
Suggestions missing

### ISSUE THREAD

**Issue by phlind** [Yeboster/autocomplete-obsidian#6]
Thanks for developing the plugin. I have the problem that words already written in a file don't show up:

![Bildschirmfoto 2021-03-08 um 12 57 57](https://user-images.githubusercontent.com/30386310/110318971-85f11980-800e-11eb-93a5-aace7e4371c9.png)

**Comment by Yeboster** [comment]
Hi!
Thanks for the bug report. 
I confirm the issue because the word is recognized only when pressing space. 
In the next release I'll fix this by adding also the `enter` key. Do you think there are other cases where the word should be added ?

**Comment by phlind** [comment]
Probably normal punctuation characters like `. , ; – - "`.

**Comment by phlind** [comment]
I also have the problem that the closest suggestion doesn't appear at the top:

![Unbenannt](https://user-images.githubusercontent.com/30386310/110351243-e85d1080-8034-11eb-9f2c-6f68a12102ce.png)

**Comment by Yeboster** [comment]
This is because you've triggered the autocomplete after writing some text. I'll enhance the trigger also to consider the current word

**Comment by Yeboster** [comment]
This is fixed in the last release. If there are any issue please reopen or open a new issue.
